### ISSUE TITLE
Sprint 2 - Retro Notes

### ISSUE THREAD

**Issue by natec425** [BaseCampCoding/ascent#20]

**Comment by william-warren** [comment]
Accomplishing provided goal points.
Team Collaboration, My bad for not being here a lot.
Be here more, more time working together.

**Comment by gillianfloyd2001** [comment]
What went well?
     - On Tuesday and Wednesday, I worked by myself and I ran into some bugs but I pushed through and Googled some of the errors. Also with that, I started reading the two scopes of django. Patton and I finished two tickets this week which is a really big plus.

**Comment by destinymalone** [comment]
Completing the app earlier than expected.
Learning about other features to incorporate while having downtime.

We were not able to work together every day because of absences.

Getting feedback on the app, so far, to figure out what more can we add to get the most out of the app.

**Comment by Christian-Guzman** [comment]
**What went well?** - Getting done with 4 tickets and balancing out the work evenly as well as making sure we knew that it is okay to be wrong and disagree.

**What didn't go well?** - Our commit messages and commits in general need some work as well as our knowledge on git.

**What should we commit to improve next sprint?** - We need to commit on making better and more comprehensive commits. Also making sure all the time is spent towards reaching our goal.

**Comment by Oscar18Guzman** [comment]
- my partner and I got to have our ideas brought to life, we were able to get our thoughts and advice across and as well as kept it productive. 
 - Something that didn't go well was attempting to get a random object from a model and working with GIT. But after a while, it started to come back to me 
 - try not to let our failures get in the way of our day and instead make cheap failures.

**Comment by devinbooker616** [comment]
**What went well?**
I personally think of the collaboration and progress that my partner and I made this week. We were quickly able to get done with two tickets and make significant headway on the third.

**What didn’t go well?**
The testing did not go the way I planned. It delayed us for a good two days, but now that we have a better idea of how to make a test and what halted our progress, that shouldn’t have such a damaging effect. 

**What should we commit to improving the next sprint?**	
I know what I said on the second answer but testing could still get better and would make the work go more smoothly.

**Comment by jiddyy** [comment]
What went well? 

A lot of things went well this week with the Shoutouts Team. We completed a total of four tickets with an even amount of work put in from both of us. 

What didn't go well?

We made a bunch of unnecessary migrations that messed up our database quite a bit, but that was resolved. We also spent a lot of time struggling with completing the 'upvote a shoutout' ticket. Also, neither of us know that much about how to use git, both of us hope to improve that in the near future.

What should we commit to improve next sprint? 

By the end of our next sprint, Christian and I will be writing better commit messages at the appropriate times, not spending so much time stuck in a hole, and reaching out to colleagues for help more often!

**Comment by Dakota-C-rgb** [comment]
What went well? 
         I feel that collaboration went fairly well for the most part. We helped each other stay on track and tackle the task at hand. The tickets kept us in the same mindset and we were able to get them done in a timely fashion. 

What didn't go well? 
        It took us about a day to actually start collaborating properly and that put a dent into the flow for a while. We didn't speak to the "project manager" all that much when we needed to. We also built the first half of the project the wrong way and had to start over. 

What should we commit to improve next sprint? 
        Making sure we are doing the right thing to complete a ticket. We also need to talk with other groups and see if we can help/receive help.

**Comment by Patton-Burge** [comment]
**What Went Well**
I feel like our progress greatly increased during this last sprint.
I think that we worked pretty hard this week. I wish I hadn't had missed this week because I feel like with both of us here we could have gotten done with a few more tickets.

**What Didn't Go Well**
I feel like we really had to be handheld through writing our tests so that something I would greatly like to improve on. I also feel that we get stuck a little too long on error messages and that we need to learn more about what the error message is telling us and what we can do to fix it. Lastly, I feel like I personally need to learn to take my hands off the keyboard sometimes and give up the driver's seat.

**What Should We Commit To Improve Next Sprint**
I feel like we can improve on our ability to respond to error messages. We could also improve on trying to be more focused on the code that we are developing.

**Comment by Tyler-Irving** [comment]
What went well?
What went well for me was staying on task during work time. 

What didn’t go well?
What didn’t go well for me was being burnt out with all the work and running into so many potholes. I keep running into countless problems, some small, that just stumped me. Another thing that did not go well is understanding how to solve the problem and not having someone to offer a different way of trying to solve the problem.

What should I commit to improving the next sprint?
Have a designed plan to complete tickets. I think taking a good 5 - 10 minutes to plan out what I’m going to do to fix the problem would help me ten-fold, and also leave something for me to look back on instead of getting lost in my thoughts.

**Comment by ASoledadU** [comment]
## What went well?
The overall work ethic. We were able to finish our 2 tickets on Wednesday. After that, we spent our time cleaning up our code to make it easier to use later on down the road. We also worked towards other tickets so we can lighten the workload for possibly next week. 

## What didn't go well?
Communication between our team with the "project manager". We worked on our code for about 2 weeks now and we thought we were on track and showed the results of our work. After deeper inspection, we came to find out that the approach we took to solve the problem wasn't the way it should have been envisioned. As a result, we have to restructure our code.

## What should we commit to improve next sprint?
Communication on expectations and understanding when to ask for help. If we could from the start to clarify what is expected and the desired results then we can save a lot of time. That also goes for if we would appropriately as for help we wouldn't be stuck for so long.

**Comment by gillianfloyd2001** [comment]
What went well?

- On Tuesday and Wednesday, I worked by myself and I ran into some bugs but I pushed through and Googled some of the errors. Also with that, I started reading the two scopes of django. Patton and I finished two tickets this week which is a really big plus.

what didn't go well?

- Something that didn't go well was getting our Submit_reflection view together. I hurt when I was not feeling my best and my partner was out and I need to get a ticket done so when he got back, this just brought me down.

 What should we commit to improve next sprint?

- Maybe we could all start writing the test first next week (TDD), but other than that I don't think there is anything else we could possible change for next sprint besides not getting so distracted but this was an issue because I didn't get enough sleep(which means I need more sleep.)

**Comment by DerekStegall** [comment]
## What went well?

> The collaboration between my partner and I has been going very well. There's not a time where discussion is not open wether its for new ideas, errors or  how to move forward.

## What didn't go well?

> When handling Github we noticed there was always an issue. To get past this we can get practice with Github.

## What should we commit to improve next sprint?

> I will commit to improving my knowledge on Github. What are the ways to push and pull?
